client_config_backend: settings
client_config:
client_id: 983337404924-upifo8k4v0abpmtjevte5g9pchvghakd.apps.googleusercontent.com
client_secret: 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: True
save_credentials_backend: file
save_credentials_file: credentials.jsonget_refresh_token: Trueoauth_scope:
- https://www.googleapis.com/auth/drive.file